var SHA1={hexcase:0,b64pad:"",chrsz:8,hex_sha1:function(a){return this.binb2hex(this.core_sha1(this.str2binb(a),a.length*this.chrsz))},b64_sha1:function(a){return this.binb2b64(this.core_sha1(this.str2binb(a),a.length*this.chrsz))},str_sha1:function(a){return this.binb2str(this.core_sha1(this.str2binb(a),a.length*this.chrsz))},hex_hmac_sha1:function(a,b){return this.binb2hex(this.core_hmac_sha1(a,b))},b64_hmac_sha1:function(a,b){return this.binb2b64(this.core_hmac_sha1(a,b))},str_hmac_sha1:function(a,
b){return this.binb2str(this.core_hmac_sha1(a,b))},sha1_vm_test:function(){return"a9993e364706816aba3e25717850c26c9cd0d89d"==this.hex_sha1("abc")},core_sha1:function(a,b){a[b>>5]|=128<<24-b%32;a[(b+64>>9<<4)+15]=b;for(var c=Array(80),d=1732584193,f=-271733879,e=-1732584194,g=271733878,i=-1009589776,j=0;j<a.length;j+=16){for(var k=d,l=f,m=e,p=g,q=i,h=0;80>h;h++){c[h]=16>h?a[j+h]:this.rol(c[h-3]^c[h-8]^c[h-14]^c[h-16],1);var s=this.safe_add(this.safe_add(this.rol(d,5),this.sha1_ft(h,f,e,g)),this.safe_add(this.safe_add(i,
c[h]),this.sha1_kt(h))),i=g,g=e,e=this.rol(f,30),f=d,d=s}d=this.safe_add(d,k);f=this.safe_add(f,l);e=this.safe_add(e,m);g=this.safe_add(g,p);i=this.safe_add(i,q)}return[d,f,e,g,i]},sha1_ft:function(a,b,c,d){return 20>a?b&c|~b&d:40>a?b^c^d:60>a?b&c|b&d|c&d:b^c^d},sha1_kt:function(a){return 20>a?1518500249:40>a?1859775393:60>a?-1894007588:-899497514},core_hmac_sha1:function(a,b){var c=this.str2binb(a);16<c.length&&(c=this.core_sha1(c,a.length*this.chrsz));for(var d=Array(16),f=Array(16),e=0;16>e;e++)d[e]=
c[e]^909522486,f[e]=c[e]^1549556828;c=this.core_sha1(d.concat(this.str2binb(b)),512+b.length*this.chrsz);return this.core_sha1(f.concat(c),672)},safe_add:function(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535},rol:function(a,b){return a<<b|a>>>32-b},str2binb:function(a){for(var b=[],c=(1<<this.chrsz)-1,d=0;d<a.length*this.chrsz;d+=this.chrsz)b[d>>5]|=(a.charCodeAt(d/this.chrsz)&c)<<32-this.chrsz-d%32;return b},binb2str:function(a){for(var b="",c=(1<<this.chrsz)-1,d=0;d<
32*a.length;d+=this.chrsz)b+=String.fromCharCode(a[d>>5]>>>32-this.chrsz-d%32&c);return b},binb2hex:function(a){for(var b=this.hexcase?"0123456789ABCDEF":"0123456789abcdef",c="",d=0;d<4*a.length;d++)c+=b.charAt(a[d>>2]>>8*(3-d%4)+4&15)+b.charAt(a[d>>2]>>8*(3-d%4)&15);return c},binb2b64:function(a){for(var b="",c=0;c<4*a.length;c+=3)for(var d=(a[c>>2]>>8*(3-c%4)&255)<<16|(a[c+1>>2]>>8*(3-(c+1)%4)&255)<<8|a[c+2>>2]>>8*(3-(c+2)%4)&255,f=0;4>f;f++)b=8*c+6*f>32*a.length?b+this.b64pad:b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(d>>
6*(3-f)&63);return b}};
function bdecode(a){function b(a,b){var c=a.indexOf(":",b);n=parseInt(a.substring(b,c));if("0"==a[b]&&c!=b+1)throw"ValueError";c++;return[a.substring(c,c+n),c+n]}var c={l:function(a,b){var d=[];for(b++;"e"!=a[b];){var e=c[a[b]](a,b),f=e[0],b=e[1];d.push(f)}return[d,b+1]},d:function(a,d){var e={};for(d++;"e"!=a[d];){var f=b(a,d),g=f[0],d=f[1],f=c[a[d]](a,d);e[g]=f[0];d=f[1]}return[e,d+1]},i:function(a,b){b++;newf=a.indexOf("e",b);n=parseInt(a.substring(b,newf));if("-"==a[b]){if("0"==a[b+1])throw"ValueError";
}else if("0"==a[b]&&newf!=b+1)throw"ValueError";return[n,newf+1]}};c["0"]=b;c["1"]=b;c["2"]=b;c["3"]=b;c["4"]=b;c["5"]=b;c["6"]=b;c["7"]=b;c["8"]=b;c["9"]=b;try{var d=c[a[0]](a,0),f=d[0],e=d[1]}catch(g){throw"Not a valid bencoded string";}if(e!=a.length)throw"invalid bencoded value (data after valid prefix)";return f}
function bencode(a){function b(a){return"[object Array]"==Object.prototype.toString.call(a)?"array":typeof a}function c(a){r=r.concat(["i",a.toString(),"e"])}r=[];encode_func={};encode_func.number=c;encode_func.array=function(a){r.push("l");for(var c=a.length,e=0;e<c;e++)encode_func[b(a[e])](a[e]);r.push("e")};encode_func.object=function(a){r.push("d");var c=[],e;for(e in a)c.push(e);c.sort();var g=c.length;for(e=0;e<g;e++){var i=c[e],j=a[i];r=r.concat([i.length.toString(),":",i]);encode_func[b(j)](j)}r.push("e")};
encode_func.string=function(a){r=r.concat([a.length.toString(),":",a])};encode_func["boolean"]=function(a){c(+a)};encode_func[b(a)](a,r);return r.join("")};
