(function(){function h(a){return(a+"").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&apos;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\s+/g,"&nbsp;")}function j(a){a.stopPropagation();a.preventDefault();return!1}function n(a){a=$.now()-a;return 6E4>=a?"刚刚":36E5>a?parseInt(a/60/1E3,10)+"分钟前":864E5>a?parseInt(a/60/60/1E3,10)+"小时前":108E6>a?(a=parseInt((nowDate-timeDate)/24/60/60/1E3,10),3>a?["今天","昨天","前天"][a]:a+"天前"):"以前"}var b={},e=this;(e.navigator.userAgent+"").match(/(?:android|iphone|ipod|ipad|ios)/i);
var m=swfobject.hasFlashPlayerVersion("10"),p=!!(e.navigator.userAgent+"").match(/(?:chrome)/i);b.maskId="x2yun_mask_"+$.now();b.drop={init:function(){function a(){c.css({width:$(e).width(),height:$(e).height()})}if(e.FileReader){$.event.props.push("dataTransfer");var c=$("#"+b.maskId),d=$("#dropTip");c.length||(c=$('<div id="'+b.maskId+'" class="mask"></div>').appendTo("body").on("click",function(){c.hide();d.hide()}));d.length||(d=$('<div id="dropTip">Drop to play</div>').appendTo("body"));$(e).on("scroll",
a);$("*").on("drop",j);$("body").on({dragenter:function(b){b.stopPropagation();b.preventDefault();a();c.show();d.show();return!1},dragover:j,dragleave:j,drop:j});$(c).on({dragenter:j,dragover:j,dragleave:function(a){a.stopPropagation();a.preventDefault();c.hide();d.hide();return!1},drop:function(a){a.stopPropagation();a.preventDefault();c.hide();d.hide();var a=a.dataTransfer||a.target||{},l=a.files||[];$.each(l,function(a,c){var d=c.name;if(d.match(/\.url$/))return b.drop.playUrl(c),!0;if(d.match(/\.torrent$/))return b.drop.playTorrent(c),
!0});if(!l.length)try{var g=a.getData("Url")||a.getData("text/uri-list")||a.getData("Text");g&&($("#u").val(h(g)),b.cleanUrl())}catch(e){}return!1}})}},playTorrent:function(a){var c=new FileReader;c.readAsBinaryString(a);c.onloadend=function(a){b.message("info","开始播放拖放的种子文件。");var c=(a.currentTarget||a.target||{}).result||"";c?($.ajaxSetup({cache:!0}),$.getScript("bdecode.sha1.js",function(){try{var a=SHA1.hex_sha1(bencode(bdecode(c).info)).toUpperCase();$("#u").val(h("magnet:?xt=urn:btih:"+
a));b.cleanUrl()}catch(d){b.message("error","无效的种子文件。")}}),$.ajaxSetup({cache:!1})):b.message("error","无效的种子文件。")}},playUrl:function(a){b.message("info","开始播放拖放的快捷方式。");var c=new FileReader;c.readAsText(a,"GBK");c.onloadend=function(a){try{var c=((a.currentTarget||a.target||{}).result||"").match(/\r\nURL=(.*?)\r\n/)[1];$("#u").val(h(c));b.cleanUrl()}catch(l){b.message("error","无效的快捷方式。")}}}};b.uploader={uploadFile:function(){if(b.uploader.uploader&&b.uploader.uploader.x2_uploader_uploadFile)return b.uploader.uploader.x2_uploader_uploadFile()},
setStyle:function(a){if(b.uploader.uploader&&b.uploader.uploader.x2_uploader_setStyle)return b.uploader.uploader.x2_uploader_setStyle(a)},uploadError:function(a){alert(6==a?"BT文件上传超时，请稍候重试":5==a?"BT文件大小超过6M，请选择其他BT文件":"BT文件上传失败，请稍候重试")},browser:function(){},uploadSuccess:function(a){if(a=jQuery.parseJSON(a)){var c=a.ret;0==c&&40==a.infohash.length?($("#u").val("magnet:?xt=urn:btih:"+a.infohash),b.cleanUrl()):b.message("error",2==c?"请求参数有误，请检查后重新添加":6==c?"该种子文件解析失败，请稍后再试":"BT文件上传失败，请稍候重试")}},uploadProgress:function(a,
c){b.message("info","正在上传 "+h(c)+" "+parseInt(100*a,10)+"%")},setFilename:function(a){b.message("info","开始上传 "+h(a))},init:function(){var a=$("#upload-button");if(a.length)if(m){var c=a.outerHeight(),d=a.outerWidth();$('<div id="uploader"><div id="_uploader"></div></div>').css({position:"absolute",left:0,top:0,width:d,height:c,cursor:"pointer"}).appendTo(a.css({position:"relative"}).off("click"));swfobject.embedSWF("//vod.xunlei.com/media/fileUploader.swf","_uploader",d,c,"10.0.0","//vod.xunlei.com/library/expressInstall.swf",
{description:"请选择BT种子文件(*.torrent)",extension:"*.torrent",timeOut:10,url:"http://dynamic.vod.lixian.xunlei.com/interface/upload_bt",label:"",limitSize:6442450944,jsPrefix:"x2.uploader.",asPrefix:"x2_uploader_",isImmediately:!0},{wmode:"transparent",allowScriptAccess:"always"},{id:"_uploader",name:"_uploader"},function(c){c.success&&(b.uploader.uploader=(-1!=e.navigator.appName.indexOf("Microsoft")?e:document)._uploader,a.prop("disabled",!1))})}else a.hide()}};b.playerId="x2yun_"+$.now();b.player=
{init:function(a){e.location.hash="!u="+encodeURIComponent(a.url);b.player.getTrialCookie();b.player.playByX2(a)},playByX2:function(a){a.url=b.encode_uri(a.url);a.name=b.encode_uri(a.name);a=$.extend(a,{encode:"x2_encode",ver:2,method:"getVideoInfo"});$.getJSON("//api.naliso.com/sqlinfoapi.php?callback=?&"+$.param(a),function(a){if(a.error)return b.message("error",a.error);a.f&&a.f.filename&&b.setVideoData({name:decodeURIComponent(a.f.filename)});if(p&&a.v&&a.v.mp4&&(a.v.mp4.l||a.v.mp4.h))return b.player.playMp4(a,
"http://gdl.lixian.vip.xunlei.com/download?"+$.param(a.v.mp4.l||a.v.mp4.h));a.v=a.v||{};a.v.file=a.v.flv||a.v.mp4;return m&&a.v&&a.v.file&&(a.v.file.l||a.v.file.h)?b.player.playFlv("http://gdl.lixian.vip.xunlei.com/download?"+$.param(a.v.file.l||a.v.file.h)):b.message("error","获取播放地址失败2")})},playFlv:function(a){flashvars={file:encodeURIComponent(a),flv:encodeURIComponent(a),path:encodeURIComponent(a),autosize:!0,src:"http://",autoplay:!0};$("#player").html('<div id="'+b.playerId+'"/>');swfobject.embedSWF("//ossweb-img.qq.com/images/bns/act/a20121023intro/video.swf",
b.playerId,"100%","100%","10.0.0","//vod.xunlei.com/library/expressInstall.swf",flashvars,{allowFullScreen:!0,allowScriptAccess:"never",bgcolor:"#000000",wmode:"opaque",quality:"high",menu:!1},{id:b.playerId,name:b.playerId})},playMp4:function(a,c){$('<video id="'+b.playerId+'"/>').attr({src:c,type:"video/mp4; codecs='avc1.42E01E, mp4a.40.2'"}).prop({autoplay:!0,preload:!0,controls:!0}).css({width:$("#player").width(),height:$("#player").height(),background:"#000"}).appendTo($("#player").html(""))},
getTrialCookie:function(){$.getScript("//dynamic.vod.lixian.xunlei.com/fx")},playByVip:function(a,b){var d="//vod.xunlei.com/client/cplayer.html?"+$.param({uvs:[b.userid,b.isvip,b.sessionid].join("_"),url:a.url});$("#player").html('<iframe style="width:100%;height:100%;" marginWidth="0" marginHeight="0" scrolling="no" frameBorder="0" src="'+d+'"></iframe>')},getXlCookie:function(a){$.getJSON("//dynamic.vod.lixian.xunlei.com/interface/getXlCookie?jsonp=?",a)}};b.play=b.player.init;var k=$("#filename"),
i=[];b.showFiles=function(a){function c(a){var b=[];$.each(a,function(a,c){var d=decodeURIComponent(c.name),d=d.slice(d.lastIndexOf("/")+1);b.push('<option value="'+c.index+'">');b.push(h(d));b.push("</option>")});return b.join("")}function d(){var c=k.find("select").val(),d={};$.each(i,function(a,b){if(b.index==c)return d=b,!0});b.play({url:"bt://"+a+"/"+d.index,name:decodeURIComponent(d.name),hash:a,index:d.index,gcid:d.gcid,cid:d.cid,filesize:d.file_size,url_hash:d.url_hash,duration:0})}a=a.toUpperCase();
if(a.match(/^[A-Z0-9]{40}$/))return b.message("info","分析磁力链或种子视频..."),$.getJSON("http://i.vod.xunlei.com/req_subBT/info_hash/"+a+"/req_num/2000/req_offset/0/?jsonp=?",function(a){if(!a||!a.resp)b.message("warning","分析磁力链或种子视频失败。");else if(i=a.resp.subfile_list||[],i.length){a=i;if(1==a.length)a=decodeURIComponent(a[0].name);else{var e=[],g={};$.each(a,function(a,b){var c=decodeURIComponent(b.name);0<c.indexOf("/")?(c=c.slice(0,c.lastIndexOf("/")),g[c]=g[c]?g[c]:[],g[c].push(b)):e.push(b)});var f=
["<select>"];f.push(c(e));$.each(g,function(a,b){b=g[a];f.push('<optgroup label="'+h(a)+'">');f.push(c(b));f.push("</optgroup>")});f.push("</select>");a=f.join("")+" 该链接包含多个视频，请选择播放。"}k.html(a).show().find("select").change(d).find("option").click(d)}}).error(function(){b.message("error","获取磁力链或种子视频失败。")})};b.setVideoData=function(a){document.title=a.name?"云点播 - "+a.name:"";k.html()||k.html(h(a.name))};b.initMessageBox=function(){function a(){b.css({top:$(e).scrollTop(),left:($(e).width()-b.width())/
2+$(e).scrollLeft()})}if(!$("#message").length){var b=$('<div id="message"><div id="message-inner"><div id="message-close">&times;</div><div id="message-body">&nbsp;</div></div></div>').appendTo("body").on("mouseover",function(){$(this).stop().css({opacity:1})});$(e).on({resize:a,scroll:a});a();b.find("#message-close").click(function(){$("#message").hide()})}};b.message=function(a,c){b.initMessageBox();if(!a||!c)return $("#message").hide();$("#message-body").html(c).attr("class",a);$("#message-close").attr("class",
a);$("#message").show().stop().css({opacity:1});"error"==a?alert(c):$("#message").fadeOut(8E3);$(e).resize()};b.encode_uri=function(a){for(var b=[],d="",e="",a=(a+"").split(""),f=0,g=a.length;f<g;f++)d=a[f],e=encodeURIComponent(d),e==d&&(e=d.charCodeAt(0).toString(16),e=("00"+e).slice(-2)),b.push(e);return b.join("").replace(/%/g,"").toUpperCase()};b.decode_uri=function(a){for(var b=[],a=a.split(""),d=0,e=a.length;d<e;d+=2)b.push("%"+a[d]+a[d+1]);return decodeURIComponent(b.join(""))};b.cleanUrl=
function(){function a(a){a.error?(b.message("error",a.error),$("#u").focus()):!a.hash&&!a.url?(b.message("error","无效的文件链接。"),$("#u").focus()):(document.title="云点播",k.html(""),i=[],a.hash?b.showFiles(a.hash).done(function(){if(i.length){var c="index"in a&&-1!=a.index?a.index:i[0].index;k.find("select").val(c);var d={};$.each(i,function(a,b){if(b.index==c)return d=b,!0});b.play({url:"bt://"+a.hash+"/"+d.index,name:decodeURIComponent(d.name),hash:a.hash,index:d.index,gcid:d.gcid,cid:d.cid,filesize:d.file_size,
url_hash:d.url_hash,duration:0})}else b.message("error","该磁力链或种子不包含视频文件。")}):b.play({url:a.url}))}var c=$.trim($("#u").val());c.match(/^[A-F0-9]{40}$/i)&&(c="magnet:?xt=urn:btih:"+c.toUpperCase());if(c.match(/^(?:http|https|ftp|thunder|mms|qqdl|rtsp|magnet|flashget|ed2k|bt|xlpan):/i)){var d=(c+"&").match(/^(magnet:\?xt=urn:btih:([A-F0-9]{40}))&/)||(c+"/").match(/^(bt:\/\/([A-F0-9]{40})\/(\d+))\//)||(c+"/").match(/^(bt:\/\/([A-F0-9]{40}))\//)||c.match(/^(xlpan:\/\/(?:.*?))$/),e=/^http:\/\/f\.xunlei\.com\/(\d+)\/file\/([a-f0-9\-]+?)\//,
f=b.encode_uri(c);d?a({index:d[3]?parseInt(d[3],10):-1,hash:d[2]?d[2]:"",url:d[1]}):c.match(/^http:\/\/(?:.*?)\.torrent$/)?(b.message("info","下载种子..."),$.getJSON("//api.naliso.com/urlapi.php?callback=?&method=downloadTorrent&u="+encodeURIComponent(f)+"&encode=x2.encode_uri",a)):(c+"/").match(e)?(b.message("info","获取迅雷盘资源..."),c=(c+"/").match(e),$.getJSON("//svr.f.xunlei.com/fileContent/getFile?callback=?&node="+encodeURIComponent(c[1]+":"+c[2]),function(c){!c||c.rtn||!c.data||!c.data.file?b.message("error","无效的迅雷盘链接..."):
(c=c.data.file,!c.vodCode||!c.path?b.message("error","无效的迅雷盘链接..."):a({url:"xlpan://"+c.vodCode+c.path}))})):(b.message("info","解析播放地址..."),$.getJSON("//api.naliso.com/urlapi.php?callback=?&method=cleanurl&u="+encodeURIComponent(f)+"&encode=x2.encode_uri",a))}else b.message("error","无效的播放地址。"),$("#u").focus()};var f=[];b.history={support:function(){return!(!e.localStorage||!e.JSON)},load:function(){if(b.history.support){var a=e.localStorage.getItem("history");f=(f=a?JSON.parse(a):[])||[]}},add:function(a){if(b.history.support){var c=
!1;$.each(f,function(b,e){e.url==a&&(c=!0,f[b].time=$.now())});c||f.unshift({url:a,time:$.now()});b.history.update()}},remove:function(a){b.history.support&&($.each(f,function(b,d){if(d.url==a)return delete f[b],!0}),b.history.update())},setTitle:function(a,c){b.history.support&&($.each(f,function(b,e){e.url==a&&(f[b].title=c)}),b.history.update())},update:function(){b.history.support&&(f=f.sort(function(a,b){return a.time>b.time?-1:1}).slice(0,20),e.localStorage.setItem("history",JSON.stringify(f)))},
show:function(){if(b.history.support){var a=initSeachResultDiv(),c=[],d=0;c.push("<ul>");$.each(f||[],function(a,b){if(b.title){d++;var e=n(b.time),f=b.url;f.match(/^[A-F0-9]{40}$/)&&(f="magnet:?xt=urn:btih:"+f);c.push('<li><a href="javascript://" data-url="'+h(f)+'">');c.push(h(b.title));c.push("<i>"+e+"</i>");c.push("</a></li>")}});c.push("</ul>");a.show().html(c.join("")+'<div class="pagination"><a href="javascript:x2.history.clear();">清</a></div>').css({height:a.find("ul").height()}).find("ul>li>a").on("click",
function(){$("#u").val($(this).data("url"));b.cleanUrl()});d||a.html('<div class="loading">无记录。</div>').css({height:200})}},clear:function(){b.history.support&&(f=[],e.localStorage.setItem("history",""),b.history.show())},init:function(){if(b.history.support){b.history.load();var a=$('<a id="history-btn" href="javascript://">看过</a>').insertBefore("#search-btn").click(function(a){a.stopPropagation();b.history.show()});$("#q").css({width:$("#q").width()-a.width()})}}};b.hashQuery=function(a){var b=
{},d=e.location.hash+"";0==d.indexOf("#%21")&&(d=decodeURIComponent(d));$.each(d.replace(/^#!/,"").split("&"),function(a,d){var e=d.match(/^(.*?)=(.*?)$/);e&&(b[e[1]]=decodeURIComponent(e[2]))});return a?b[a]:b};$(document).ready(function(){e!==e.top&&$("#video").css({"margin-top":25});$("#play-button").click(function(a){j(a);b.cleanUrl()});b.initMessageBox();b.uploader.init();b.drop.init();!$("#u").val()&&b.hashQuery("u")&&$("#u").val(b.hashQuery("u").split("#")[0]);$("#u").val()&&b.cleanUrl()});
e.x2=b})();
